par(pty="s")
plot(matrix(c(3,3,6,6), 2, 2, byrow = TRUE), type = "n", xlab = "", ylab = "")
x <- seq(-2*pi, 2*pi, length = 100)
xx <- cbind(sin(x), cos(x))
lines(xx + 5)
lines(xx + 4)
text(5, 4, "AB")
text(4, 5, "A")
text(5, 6, "B")
text(4 - sqrt(1 / 2), 4 - sqrt(1 / 2), "A")
text(4 + sqrt(1 / 2), 4 + sqrt(1 / 2), "B")
