---
title: "approx"
author: "Jan de Leeuw"
format: pdf
---

$$
\sigma(X)=\sum w_{ij}(\delta_{ij}-d_{ij}(X))^2=
\sum \frac{w_{ij}}{(\delta_{ij}+d_{ij}(X))^2}
(\delta_{ij}^2-d_{ij}^2(X))^2\approx\frac14\sum \frac{w_{ij}}{\delta_{ij}^2}
(\delta_{ij}^2-d_{ij}^2(X))^2
$$
Now consider the problem of minimizing sstress. 
$$
\sigma(X)=\sum w_{ij}(\delta_{ij}^2-d_{ij}^2(X))^2.
$$
Define $A_{ij}$ as usual, $C=XX'$, $a_{ij}=\text{vec}(A_{ij})$, an d $c=\text{vec}(C)$. Then $d_{ij}^2(X)=\text{tr}\ A_{ij}C=a_{ij}'c$, and thus
$$
\sigma(C)=K-2\text{tr}\ BC+c'Vc
$$
$$
B=\sum w_{ij}\delta_{ij}^2A_{ij}
$$
$$
V=\sum w_{ij}a_{ij}a_{ij}'
$$
Let $\lambda_$ the largest eigenvalue of $V$. Now write $C=\tilde C+(C-\tilde C)$.
Then
$$
\sigma(C)\leq\sigma(\tilde C)-2\text{tr}\ (B-\tilde CV)(C-\tilde C)+\lambda_+\text{tr}\ (C-\tilde C)^2
$$
Thus we can majorize by minimizing
$$
\text{tr}\ (C-(\tilde C-\lambda_+^{-1}(B-\tilde CV)))^2
$$
over $C=XX'$.

The largest eigenvalue of $V$ is also the largest eigenvalue of
the matrix with elements $A'WA$, which is a matrix
with all elements non-negative.


# Part 2

$$
\sigma(X)=\text{tr}\ (C-XX')^2
$$
to be minimized over $n\times p$ matrices $X$.

Use the short SVD $X=K\Lambda L'$ and minimize over $K'K=I$, 
$L'L=LL=I$, and $\Lambda$ diagonal.
$$
\sigma(K,L,\Lambda)=\text{tr}\ (C-K\Lambda^2 K')^2=\text{tr}\ C^2-2\text{tr}\ \Lambda^2K'CK+\text{tr}\ \Lambda^4.
$$
The minimum over $\Lambda^2$ is attained for $\Lambda^2=\text{diag}\ K'CK$.

Now maximize $\text{tr}\ \Lambda^2K'CK$ over $K'K=I$. If $C\gtrsim 0$ this
is convex in $K$, and thus we have the minorization at $U'U=I$
$$
\text{tr}\ \Lambda^2K'CK\geq\text{tr}\ \Lambda^2U'CU+2\text{tr}\ \Lambda^2U'C(K-U)
$$
Thus it suffices to increase $\text{tr}\ K'CU\Lambda^2$, which we can
actually maximize by orthogonal Procrustus and increase by Gram-Schmidt
same reasoning as in homals).
